# Generated by Django 3.2.9 on 2021-11-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('trans', models.TextField()),
                ('symbol', models.TextField()),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
